### ISSUE TITLE
about pyinstaller package 

### ISSUE THREAD

**Issue by cwjjun** [chaofengc/IQA-PyTorch#102]
I tried to use pyinstaller to package the code containing your library, and I got a FileNotFoundError at runtime in File "pyiqa\utils\misc.py", line 76, in _scandir. How should I solve this problem? thank you!

**Comment by chaofengc** [comment]
Thanks for interest. The current codes are not tested with `pyinstaller`. Please follow instructions in readme to install the package.
```
# Install with pip
pip install pyiqa

# Install latest github version
pip uninstall pyiqa # if have older version installed already 
pip install git+https://github.com/chaofengc/IQA-PyTorch.git

# Install with git clone
git clone https://github.com/chaofengc/IQA-PyTorch.git
cd IQA-PyTorch
pip install -r requirements.txt
python setup.py develop
```
