### ISSUE TITLE
Question about SSIM

### ISSUE THREAD

**Issue by Shecyy** [chaofengc/IQA-PyTorch#105]
您好，在IQA-Pytorch 0.1.7版本中，pyiqa.archs.ssim_arch.py文件的函数def ssim():中，您使用了cs_map = F.relu(cs_map)来避免负数。请问这一步是从什么参考文献中来的哇？在其他的ssim实现版本中未发现这个计算步骤。例如：https://github.com/Po-Hsun-Su/pytorch-ssim/blob/master/pytorch_ssim/__init__.py

**Comment by chaofengc** [comment]
这仅仅是为了保证最后的结果在0-1之间，这在某些情况下会有好处。
而小于零的数值，在大多数情况下对于ssim来说并没有太大的意义。

主要参考了以下实现:
https://github.com/dingkeyan93/IQA-optimization/blob/master/IQA_pytorch/SSIM.py
