### ISSUE TITLE
关于评价指标brisque的问题。

### ISSUE THREAD

**Issue by Shecyy** [chaofengc/IQA-PyTorch#106]
作者，您好。我在使用brisque评价指标的时候，该指标的test_y_channel参数取值为True时，程序可以正常运行。但将其设置为False时，程序报错。我的输入图像的shape是[3, 400, 600]。错误信息为：RuntimeError: Given groups=1, weight of size [1, 1, 7, 7], expected input[1, 3, 406, 606] to have 1 channels, but got 3 channels instead。目前，我使用的pyiqa版本是0.6.4.1

**Comment by chaofengc** [comment]
我们的BRISQUE模型是直接用的官方模型: https://github.com/utlive/BRISQUE
目前仅支持评估纹理，不支持颜色的评价。另外，BRISQUE提出的时候，也并未考虑颜色的影响。
对于一些比较旧的metric，请不要尝试更改默认设定，这可能会有比较大的影响。

**Comment by Shecyy** [comment]
好的。非常感谢您的回复。
