### ISSUE TITLE
Multiple validation datasets are *only* supported by SRModel

### ISSUE THREAD

**Issue by Alexkkir** [chaofengc/IQA-PyTorch#108]
Hello! Thanks for awesome libarary. 

When running training with 2 validation datasets KonIQ-10k and CLIVE i rreceived warning:
`'Multiple validation datasets are *only* supported by SRModel.'`

Can you please explain, why multiple validation datasets are not supported by IQA models? It looks, like it's similar things.

**Comment by chaofengc** [comment]
Thanks for your interest!

Please just ignore such warning. Our library architecture is based on [BasicSR](https://github.com/XPixelGroup/BasicSR). Lots of modifications are made for IQA task, but still left some unnecessary codes and warnings. I will clean the codes in the near future.
