### ISSUE TITLE
Why this package require `tb-nightly`?

### ISSUE THREAD

**Issue by fansuregrin** [chaofengc/IQA-PyTorch#111]
When I install this package, pip reminds me I must install `tb-nightly`, but if I install `tb-nightly`, it will conflict with `tensorboard`. I think this needn't rely on `tb-nightly`, it is weird.

the error message is:
```
pyiqa 0.1.7 requires tb-nightly, which is not installed.
```

**Comment by chaofengc** [comment]
Thanks for your info. The package does not depend on tb-nightly, has fixed in latest commits.

Besides, the `pyiqa` library should work well without tb-nightly installed. You can proceed to use it and ignore the warning.
