### ISSUE TITLE
Dataset of the topiq_fr model

### ISSUE THREAD

**Issue by Alidaling** [chaofengc/IQA-PyTorch#112]
Are the training data used for the topiq_fr model and the topiq_fr-pipal model different? What are the specific datasets used to train them?Thanks!

**Comment by chaofengc** [comment]
Yes, the model is generally named with `[model variant]-[dataset]`. The default setting is given at the document: https://iqa-pytorch.readthedocs.io/en/latest/benchmark.html#performance-evaluation-protocol.

For your question, `topiq_fr` is trained with *kadid* dataset, and `topiq_fr-pipal` is trained with *pipal* dataset.
