### ISSUE TITLE
can topic used as loss?

### ISSUE THREAD

**Issue by Feynman1999** [chaofengc/IQA-PyTorch#117]
hello! can topic net's feature used as loss calculation for restoration tasks?

**Comment by chaofengc** [comment]
Yes, but according to my experiment, such loss does not bring advantages.

**Comment by chenkang455** [comment]
> Yes, but according to my experiment, such loss does not bring advantages.

This idea is interesting. Is there any related literature?

**Comment by chaofengc** [comment]
You may refer to [this paper](https://arxiv.org/abs/2005.01338)

**Comment by chenkang455** [comment]
> You may refer to [this paper](https://arxiv.org/abs/2005.01338)

thanks a lot！
