### ISSUE TITLE
Question about the code in pyiqa/data/transforms.py

### ISSUE THREAD

**Issue by star-journey** [chaofengc/IQA-PyTorch#120]
Your code is so awesome that I borrowed some of your code when I tried to write my own. But I unexpectedly found that the same function is used in `pyiqa/data/transforms.py`. 

https://github.com/chaofengc/IQA-PyTorch/blob/c36d31c25f1a059064e8fbee42f8b44df12c6469/pyiqa/data/transforms.py#L17-L20

Is this a mistake?

**Comment by chaofengc** [comment]
Yes, that's a mistake 😅 . Thank you so much for help ! Fixed in latest commit.
