### ISSUE TITLE
2AFC score on BAPPS

### ISSUE THREAD

**Issue by h4nwei** [chaofengc/IQA-PyTorch#121]
Hi @chaofengc ,

Thanks for the excellent IQA benchmarking project. Can you also provide one example of calculating the 2AFC scores on BAPPS? 

Best,
Hanwei

**Comment by chaofengc** [comment]
Thanks for interest ! Please refer to the following lines:
https://github.com/chaofengc/IQA-PyTorch/blob/9e6acb29cb665250896411aa3f57bbf02a0773dd/pyiqa/metrics/other_metrics.py#L6-L9

And the original codes for help:
https://github.com/richzhang/PerceptualSimilarity/blob/1fd355217ed32b88b7637591cf486cc197de043d/lpips/trainer.py#L208-L241
