### ISSUE TITLE
Source type validation not detecting PIL image correctly

### ISSUE THREAD

**Issue by ThereforeGames** [chaofengc/IQA-PyTorch#123]
Hi,

Per #40, the validation logic of source types does not account for valid subtypes of `PIL.Image.Image`, such as `PIL.JpegImagePlugin.JpegImageFile`.

The relevant code is line 29 of `img_util.py`:

```
elif type(img_source) == Image.Image:
```

I believe using `isinstance()` here may be a better approach:

```
elif isinstance(img_source, Image.Image):
```

**Comment by chaofengc** [comment]
Thanks for your help ! Fixed at https://github.com/chaofengc/IQA-PyTorch/commit/ddfb97329ccd299a47d13ce4a1a865ecaaa3721c
