### ISSUE TITLE
Question about Maniqa

### ISSUE THREAD

**Issue by wanduoz** [chaofengc/IQA-PyTorch#126]
Hello, I ran official [maniqa](https://github.com/IIGROUP/MANIQA) inference code and got iqa score: 0.2243. Then I tested Maniqa provided in IQA-PyTorch using same image. But I got different iqa score: 0.0962. Any idea why this happened? 
Thank you.

![image](https://github.com/chaofengc/IQA-PyTorch/assets/33130310/e45a439f-def5-48af-9bef-182e93c20519)
![image](https://github.com/chaofengc/IQA-PyTorch/assets/33130310/1735c3db-d6ab-4352-89cc-544b189db789)

**Comment by chaofengc** [comment]
Please check which model you used. Here is the configuration of pyiqa, default `maniqa` is trained with koniq:

https://github.com/chaofengc/IQA-PyTorch/blob/ddfb97329ccd299a47d13ce4a1a865ecaaa3721c/pyiqa/default_model_configs.py#L273-L300

**Comment by chaofengc** [comment]
Thanks for your help. After checking the code, I found this is caused by hyper parameter setting. MANIQA with koniq10k used a different `scale` parameter, fixed as below:
https://github.com/chaofengc/IQA-PyTorch/blob/33a28297236364a8db2916c1f64e97c545b6de24/pyiqa/default_model_configs.py#L273-L278

It should give similar scores as official code.

**Comment by wanduoz** [comment]
Hi. 
After fixing the code, I got iqa score=0.2394, while the official maniqa score of same image was 0.2243. I wonder if this result is reasonable?
Also, I currently used  16 iqa models and I found that the **Results Calibration** only covered parts of the following models. Due to the mismatching of **Maniqa**, do I need to check the below models score with the official results one by one? 
```
Calibrated: 'musiq-paq2piq', 'musiq-koniq', 'musiq-spaq', 'musiq-ava', 'paq2piq'

Unknown:  'clipiqa+_rn50_512', 'clipiqa+',  'dbcnn', 'clipiqa+_vitL14_512', 'tres-koniq', 
           'tres-flive', clipiqa', 'cnniqa', ', 'topiq_nr',  'hyperiqa', 'maniqa',
```

**Comment by chaofengc** [comment]
For the `maniqa` if you want to get more close results, you must control the random cropping process. I suggest you to dive deep into the codes and find the problem. 

For the models you mentioned without calibration, part of them such as `maniqa` are taken from official codes with few modifications, therefore does not provide calibration. Others have no official models or weights and are reimplemented and retrained.

It would be very helpful if you could help to double check them one by one.
