### ISSUE TITLE
Error when making more than one inference with the topiq_nr-face metric

### ISSUE THREAD

**Issue by sperezs95** [chaofengc/IQA-PyTorch#131]
Hello everyone!

First of all I want to congratulate you for such **excellent work**, I have been experimenting with this repository a few days ago, I ran into a problem when using topiq_nr-face, if I make **two or more inferences** it gives me an error:

<img width="801" alt="image" src="https://github.com/chaofengc/IQA-PyTorch/assets/75050569/1d674d9f-a916-4078-9800-a2f91142c150">

I did this test in the original **demo notebook** only changing the name of the metric, if I run the line that defines the "iqa" object again I can make an inference again, but it fails again in the second one.

I hope I'm not making any rookie mistakes.

Thank you and I will be attentive to your comments.

**Comment by chaofengc** [comment]
Thanks to your feedback. The bug has been fixed at latest commit.
