### ISSUE TITLE
关于PSNR和MSE计算的问题

### ISSUE THREAD

**Issue by SmileShaun** [chaofengc/IQA-PyTorch#132]
根据计算公式，PSNR和MSE之间应该是反比关系，即PSNR越大则MSE越小。我对两个baseline进行测试，使用pyiqa计算PSNR、F.mse_loss()计算MSE，结果PSNR高的模型MSE也高，请问这是什么原因呢？谢谢。

**Comment by chaofengc** [comment]
You may check the following code of how we calculate PSNR:
https://github.com/chaofengc/IQA-PyTorch/blob/bc7ecb335d68a564549821b4df37d4f8bde16c5c/pyiqa/archs/psnr_arch.py#L39-L40
