### ISSUE TITLE
计算节点没有联网导致无法运行代码

### ISSUE THREAD

**Issue by Acnext** [chaofengc/IQA-PyTorch#135]
你好，服务器的计算节点不能访问网络(主控可以)，但是代码运行都会在计算节点上，因此无法下载得到模型。请问有没有离线的方式(比如先在别处下载模型)？如果有，怎么操作呢？

**Comment by chaofengc** [comment]
你可以手动下载所需模型，并放到以下服务器文件夹: ``.cache/torch/hub/checkpoints``

**Comment by Acnext** [comment]
> 你可以手动下载所需模型，并放到以下服务器文件夹: `.cache/torch/hub/checkpoints`
好的多谢，这种方式确实可以。不过又遇到一个问题，有的指标，例如，niqe，如果因为网络运行失败会返回模型网址。但是其他指标，例如，TOPIQ，我没有发现模型所在网址。有没有什么方式能获得模型网址吗？

**Comment by chaofengc** [comment]
你可以在对应metric文件的开头找到链接，例如:

https://github.com/chaofengc/IQA-PyTorch/blob/96f24ae7e3f16bd59aece7ea409d5b73949d7f45/pyiqa/archs/topiq_arch.py#L31-L40

**Comment by Acnext** [comment]
好的谢谢
