### ISSUE TITLE
如何使用这个工具在自己构建的训练和测试集上做训练呢

### ISSUE THREAD

**Issue by RollingWang** [chaofengc/IQA-PyTorch#139]

**Comment by chaofengc** [comment]
由于时间和精力有限，我暂时不能提供详细的训练相关的教程。如有需求，请自行阅读代码，并参考一下BasicSR相关资料:

- https://github.com/XPixelGroup/BasicSR
- https://github.com/XPixelGroup/BasicSR-docs
- https://www.zhihu.com/column/c_1295528110138163200
