### ISSUE TITLE
请问两张相同的图的psnr结果为什么不为1或者100呢

### ISSUE THREAD

**Issue by irsLu** [chaofengc/IQA-PyTorch#148]
![image](https://github.com/chaofengc/IQA-PyTorch/assets/42465965/87ea8d2f-e7a8-419a-8008-2b2b88f5078d)
如图，我对同一张图片做psnr，结果是80，很抱歉问了个很基础的问题，但是我的确很困惑

**Comment by chaofengc** [comment]
请参考Wikipedia PSNR: https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio
以及本repo对应代码:
https://github.com/chaofengc/IQA-PyTorch/blob/27fa5fc2d30689388aee55997d964e235be6056f/pyiqa/archs/psnr_arch.py#L39-L40
