### ISSUE TITLE
Retrain topiq on LIVEChallenge dataset

### ISSUE THREAD

**Issue by joe17maker** [chaofengc/IQA-PyTorch#156]
I traind TOPIQ on CLIVE dataset, and the result is bit lower than the benchmark.
![image](https://github.com/chaofengc/IQA-PyTorch/assets/65492300/429408da-8a5c-4421-a634-c822341f010f)
I want to know if there is something wrong with my opt file，or I would be very grateful if you could provide the opt file of CLIVE.
My opt file is like below:
![image](https://github.com/chaofengc/IQA-PyTorch/assets/65492300/7338ff24-1540-4592-b02a-ae6b95abfc89)
![image](https://github.com/chaofengc/IQA-PyTorch/assets/65492300/789d925e-6b1d-4da8-aa57-bec5211dd9ba)
![image](https://github.com/chaofengc/IQA-PyTorch/assets/65492300/dfbdb6ad-bc41-4ccd-8c90-aa2483d02160)
![image](https://github.com/chaofengc/IQA-PyTorch/assets/65492300/2521d3b2-1b4f-4563-85de-86b3cc012035)

**Comment by chaofengc** [comment]
Please try to normalize the score to [0, 1] as suggested in the paper.

**Comment by joe17maker** [comment]
Thanks!
