### ISSUE TITLE
Testing on multiple dataset splits

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [chaofengc/IQA-PyTorch#162]
Hi @chaofengc 

I need to train a generic model (e.g. CLIP-IQA+) on a custom dataset. Since the dataset is quite small, I have generated 10 random splits composed of training, validation and test. I can successfully train and validate a different version of the model for each random split using ```train_nsplits.py```. However, for each split, I need to evaluate the performance of the best model (according to the validation metrics) on the test split, and it seems to me that the repo doesn't support this feature currently.

Therefore I wanted to ask you what would be the easiest way to implement testing on multiple dataset splits using the best model.

Thanks in advance

**Comment by chaofengc** [comment]
The current implementation does not support updating test results based on the performance of the validation split. To achieve this with minimal code changes, you can follow these steps:

- Add the test split in config file like:
```
val_0:
  name: validation_set
  split: split_idx
  override_phase: val

val_1:
  name: test_set
  split: split_idx
  override_phase: test
``` 
- Modify the conditions when update the results of test validation in the following codes:
https://github.com/chaofengc/IQA-PyTorch/blob/9f9e8cdae11883b3deb1f59c9ee16159d7321b6e/pyiqa/models/general_iqa_model.py#L202-L205

Here is an example modification for lines 204-205, using an additional flag to update metrics based on validation performance:
```
if dataset_name == 'xxx':
      self.to_update = self._update_best_metric_result...
```
This method is somewhat of a workaround, but it should meet your requirements without necessitating extensive changes to the existing codebase.

**Comment by LorenzoAgnolucci** [comment]
Thank you very much @chaofengc!

I did exactly as you suggested and everything worked smoothly.
