### ISSUE TITLE
Implementation of Perception based Image Quality Evaluator (PIQE)?

### ISSUE THREAD

**Issue by chenkang455** [chaofengc/IQA-PyTorch#173]
Hi, thanks for your nice work. Will you consider add the PIQE non-reference metric?

**Comment by chaofengc** [comment]
Thank you for your interest. I will consider adding PIQE when I have time.

**Comment by chenkang455** [comment]
> Thank you for your interest. I will consider adding PIQE when I have time.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

thx🥳

**Comment by chaofengc** [comment]
Thank you for your suggestion! The `piqe` has been added in the latest development version. You can now access it by installing the bleeding-edge version using the following steps:

```
# Uninstall any existing version of pyiqa
pip uninstall pyiqa

# Install the latest version directly from GitHub
pip install git+https://github.com/chaofengc/IQA-PyTorch.git
```
