### ISSUE TITLE
How can I quickly determine the value range of the evaluation indicators?

### ISSUE THREAD

**Issue by jaycecd** [chaofengc/IQA-PyTorch#174]
I greatly appreciate the author's work, which has greatly improved the efficiency of evaluating images!

Especially the `DEFAULT_CONFIGS` provide a rough statistical overview of the metrics, which is very convenient:
![image](https://github.com/user-attachments/assets/cc68f718-8f26-4f05-ad25-57a41d2f64a7)

However, this file does not include the specific value range of the metrics, and only through the `lower_better` field can we roughly judge whether the metric is better when lower or higher. 

Could you please add a field to display the value range of the metrics, so that it can clearly guide the specific quality of the generated images?

**Comment by chaofengc** [comment]
Thank you for your suggestion. Determining the range for each metric can indeed be a tedious task, especially since some metrics may not have exact value ranges. Here are the preliminary results for some metrics: [ModelCard - Outputs of Different Metrics](https://github.com/chaofengc/IQA-PyTorch/blob/main/docs/ModelCard.md#outputs-of-different-metrics).

I will update the others as time permits.

**Comment by jaycecd** [comment]
‌‌I would like to thank you again for your work. Although determining the range of indicators can be a bit tedious, it allows for a better comparison of image quality and also helps to determine if `pyiqa` is being used correctly. For example, if the range of a certain indicator is `0-1`, but the result is not within this range, it is clear that there is a problem with the way `pyiqa` is being used.

**Comment by chaofengc** [comment]
This is indeed one problem when trying to give the range. Because many metrics are trained on specific datasets with linear regression as the final layer, there is no strict regularization on the output range. It is only possible to give typical value ranges for most metrics.

**Comment by jaycecd** [comment]
Your opinion is absolutely right, and it's indeed valuable to be within the same range, and not directly compare different indicators. Therefore, it's even more necessary to clarify the range of the indicators. 

A real question is: actually, comparing different indicators isn't that important, what's more important is, under the current indicator, what level is my image at? 

For example, if a certain indicator's range is 0-1 (assuming the higher the better), and my image's result is 0.9, that already shows my image is at an "excellent" level under this indicator!

I think this is already enough, no need to pursue perfection, perfection often requires too much effort, as long as it's clearer than it is now, even if it's just a little bit, that's already a huge improvement!

**Comment by chaofengc** [comment]
Thank you for your suggestion! A rough value range has now been added to each metric, which can be accessed via `metric.score_range`.

**Please note that these ranges represent rough typical values and should NOT be used for exact normalization of metric scores.**

**Comment by jaycecd** [comment]
‌‌Thank you very much for your hard work, I'll install and try it out right away.

**Comment by jaycecd** [comment]
Hello, the value range of the new version is great! But I found there might be a tiny error where the Q-Align value range should be [1,5]. I've already submitted a relevant fix #180 . 

Let me know if I misunderstood something~
