### ISSUE TITLE
qalign

### ISSUE THREAD

**Issue by lyf-fzu** [chaofengc/IQA-PyTorch#179]
你好，我在运行model = pyiqa.create_metric('qalign').cuda() 时，命令框里面的进度条一直不动弹：

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

请问这样的话该如何解决呢

**Comment by chaofengc** [comment]
该模型权重存放在huggingface上，如果你在中国大陆，可能会遇到网络问题。
