### ISSUE TITLE
A problem on hypernet_arch.py

### ISSUE THREAD

**Issue by leonmakise** [chaofengc/IQA-PyTorch#183]
https://github.com/chaofengc/IQA-PyTorch/blob/3c6ebdc41f249bac1a0e97617bcfc3fa1a2ba7c5/pyiqa/archs/hypernet_arch.py#L185

The results after unsqueeze(-1) do not match the size of labels for computing metrics. It may cause error when calculating plcc. Should it be 'return results'？

**Comment by chaofengc** [comment]
We maintain the output shape as `(B, C)` for two key reasons:

1. **Consistency and Convenience**: This shape aligns with the mos shape output from PyTorch datasets, making it more straightforward for training purposes.
   
2. **Flexibility for Extensions**: Some methods, like `qalign`, train the IQA model as a classification problem. Keeping the output shape as `(B, C)` allows for easy adaptation to such cases.

You can simply squeeze the results before computing the PLCC
