### ISSUE TITLE
qalign离线模型问题

### ISSUE THREAD

**Issue by zhuyeqing** [chaofengc/IQA-PyTorch#185]
你好，
     非常感谢你贡献的这个开源库，我在使用时遇上了模型下载的问题：
    1）我在国内找到了huggingface的镜像库，那qalign的具体模型是哪一个？搜索qalign会有很多结果。
    2）如何在调用iqa时，设置离线模式？我在代码中设置没有生效，我的代码如下：

import os

os.environ["HF_HUB_OFFLINE"] = "1"

import pyiqa
import torch

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

iaa_metric = pyiqa.create_metric('qalign', device=device)

pic_dir = "./pic"
for f in os.listdir(pic_dir):
    pic = pic_dir + "/" + f
    score = iaa_metric(pic)
    print("文件：%s -- 分数：%s" % (f, score))

       期盼回复，多谢多谢

**Comment by zhuyeqing** [comment]
同时，我还测试过：1）在 bash_profile 添加HF_ENDPOINT 2）在代码中设置 os.environ["HF_ENDPOINT"] = "https://hf-mirror.com" 但是好像都没有效果

**Comment by chaofengc** [comment]
qalign模型名称见如下代码:
https://github.com/chaofengc/IQA-PyTorch/blob/26d2910b0b23be63bbd8855329cac89e4c1c4846/pyiqa/archs/qalign_arch.py#L49

如果想使用离线模型，可以尝试把下载好的模型放在huggingface默认的cache路径下面

**Comment by zhuyeqing** [comment]
解决办法可以参考：https://zhuanlan.zhihu.com/p/699627145

**Comment by chaofengc** [comment]
感谢你的信息！设定镜像节点应该也是有用的，请遵循hf-mirror官方教程，**并仔细检查是否成功**，样例如下:
```
export HF_ENDPOINT=https://hf-mirror.com
echo $HF_ENDPOINT
```
如果使用windows系统需要做对应设置。
