### ISSUE TITLE
关于NIMA模型的加载

### ISSUE THREAD

**Issue by QiaoYang-CV** [chaofengc/IQA-PyTorch#195]
作者您好，开源的工作使得很多人受益，谢谢您们的工作。但有如下问题：

1.当我运行如下代码的时候：
iqa_metric = pyiqa.create_metric('nima').cuda()
报如下错误：
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
之后我通过在Issues中的一些问题，下载了“NIMA_InceptionV2_ava-b0c77c00.pth”，并修改代码为：
iqa_metric = pyiqa.create_metric('nima', pretrained_model_path='/home/ununtu/.cache/torch/hub/checkpoints/NIMA_InceptionV2_ava-b0c77c00.pth').cuda()
 可是上述代码仍然报相同的错误。我不知道该怎么修改代码来保证计算nima的指标能正确运行。
 2.能否给出一般性的方法直接导入预训练模型来获得结果呢？有时候开启VPN代理不稳定，导致从相应url下载pth文件时均是失败的。
 
 期待您的解答。

**Comment by chaofengc** [comment]
这是由于国内访问huggingface网站的问题，你可以尝试使用huggingface在国内的mirror: https://hf-mirror.com/

**Comment by QiaoYang-CV** [comment]
好的，谢谢您的回答，代码已解决和跑通。具体来说我在自己的第三库下添加了
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
添加位置是：
自己环境中/site-packages\huggingface_hub\__init__.py的import os之后

**Comment by chaofengc** [comment]
更直接的方法是添加环境变量，请参考hf-mirror官方网站 https://hf-mirror.com/
```
export HF_ENDPOINT=https://hf-mirror.com
```
下载失败也可能是因为本地或者服务器端网络问题

**Comment by InTheFuture7** [comment]
@chaofengc 请问，有完全从本地加载模型的方法吗？

**Comment by InTheFuture7** [comment]
https://github.com/chaofengc/IQA-PyTorch/issues/195#issuecomment-3146117700

这个方法尝试后仍不能解决问题

**Comment by chaofengc** [comment]
你可以仿照如下方法，使用`load_weights`函数加载模型
```
iqa_metric = pyiqa.create_metric('topiq_nr', device=device, **custom_opts)

# Note that if you train the model with this package, the weights will be saved in weight_dict['params']. Otherwise, please set weight_keys=None.
iqa_metric.load_weights('path/to/weights.pth', weight_keys='params')
```

**Comment by InTheFuture7** [comment]
还是不行，我想问题是不是出在：/timm/resnet50.a1_in1k/上面，可能是没找到这个模型，所以访问huggingface去下载。

我看源码中没有找到加载这个 /timm/resnet50.a1_in1k 模型的代码，不知道是否可以手动加载

```
import pyiqa
iqa_metric = pyiqa.create_metric('hyperiqa', pretrained=False)
iqa_metric.load_weights('xxx/pretrain/HyperIQA-resnet50-koniq10k-c96c41b1.pth')
```

报错：

```
SSLError: (MaxRetryError("HTTPSConnectionPool(host='hf-mirror.com', port=443): Max retries exceeded with url: /timm/resnet50.a1_in1k/resolve/main/model.safetensors (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1149)')))"), '(Request ID: 81adeaa7-9fcd-448f-b9d9-9801a5eeb0b3)')
```

**Comment by chaofengc** [comment]
你可以把timm的自动下载设为False:
https://github.com/chaofengc/IQA-PyTorch/blob/4fd66f3d883ae6f6726872d1dfbefc156bf8780a/pyiqa/archs/hypernet_arch.py#L58-L60

**Comment by InTheFuture7** [comment]
修改后输出如下，loading时遇到一个typeerror

```
Loading pretrained model HyperNet from xxx/pretrain/HyperIQA-resnet50-koniq10k-c96c41b1.pth

----> 1 hyperiqa_metric = pyiqa.create_metric('hyperiqa', pretrained_model_path='xxx/pretrain/HyperIQA-resnet50-koniq10k-c96c41b1.pth')

File ~/devTool/anaconda3/envs/model/lib/python3.8/site-packages/pyiqa/api_helpers.py:12, in create_metric(metric_name, as_loss, device, **kwargs)
---> 12     metric = InferenceModel(metric_name, as_loss=as_loss, device=device, **kwargs)

File ~/devTool/anaconda3/envs/model/lib/python3.8/site-packages/pyiqa/models/inference_model.py:61, in InferenceModel.__init__(self, metric_name, as_loss, loss_weight, loss_reduction, device, seed, check_input_range, **kwargs)
---> 61 self.net = build_network(net_opts)

File ~/devTool/anaconda3/envs/model/lib/python3.8/site-packages/pyiqa/archs/__init__.py:138, in build_network(opt)
--> 138 net = ARCH_REGISTRY.get(network_type)(**opt)

File ~/devTool/anaconda3/envs/model/lib/python3.8/site-packages/pyiqa/archs/hypernet_arch.py:129, in HyperNet.__init__(self, base_model_name, num_crop, pretrained, pretrained_model_path, default_mean, default_std)
--> 129     load_pretrained_network(self, pretrained_model_path, True, weight_keys='params')

File ~/devTool/anaconda3/envs/model/lib/python3.8/site-packages/pyiqa/archs/arch_util.py:203, in load_pretrained_network(net, model_path, strict, weight_keys)
--> 203 state_dict = torch.load(model_path, map_location=torch.device("cpu"), weights_only=False)

File ~/devTool/anaconda3/envs/model/lib/python3.8/site-packages/torch/serialization.py:1047, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
--> 712         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)

File ~/devTool/anaconda3/envs/model/lib/python3.8/site-packages/torch/serialization.py:1047, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
-> 1047 unpickler = UnpicklerWrapper(data_file, **pickle_load_args)

TypeError: 'weights_only' is an invalid keyword argument for Unpickler()
```

**Comment by InTheFuture7** [comment]
还是没有解决这个问题😓，梳理一下

我已经在下载了HyperIQA-resnet50-koniq10k-c96c41b1.pth到服务器上，执行下面的代码，会报错 `SSLError: (MaxRetryError("HTTPSConnectionPool(host='hf-mirror.com' Max retries exceeded with url: /timm/inception_resnet_v2.tf_in1k/resolve/main/model.safetensors (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1149)')))")`

```
hyperiqa_metric = pyiqa.create_metric('hyperiqa', pretrained_model_path='/Data/wangsipeng/SMPP/Ours/multimodal_framework/pretrain/HyperIQA-resnet50-koniq10k-c96c41b1.pth')
```

根据 `/timm/inception_resnet_v2.tf_in1k/resolve/main/model.safetensors `，猜测是服务器没有下载这个 `/timm/inception_resnet_v2` 模型。

然后我下载了这个 `/timm/resnet50.a1_in1k` 模型，并且设置 ` self.base_model = timm.create_model(base_model_name, pretrained=False, features_only=True)`，还是有新的报错`TypeError: 'weights_only' is an invalid keyword argument for Unpickler()`。

现在的问题是不是，需要调用代码来加载 `/timm/resnet50.a1_in1k` 模型？ @chaofengc

**Comment by chaofengc** [comment]
这个是你的pytorch版本太低了

**Comment by InTheFuture7** [comment]
我用的刚好是1.12.0

**Comment by InTheFuture7** [comment]
感谢，刚试了1.12.1也不行，正要尝试1.13

**Comment by InTheFuture7** [comment]
@chaofengc  泪目了，大佬，我终于跑出来了。

因为网络、硬盘空间等问题，换了几台服务器，终于跑出结果了。非常感谢

确实版本要求要是  pytorch >= 1.13.0

**Comment by InTheFuture7** [comment]
@chaofengc 
我整理一份关于离线加载模型的文档，希望对项目和其他朋友们有帮助，再次感谢大佬的耐心解答😁

https://gist.github.com/InTheFuture7/9679c9969700a5759801f85f92fcb2b4
