### ISSUE TITLE
"pyiqa.creat_metric" failed because of the "connection timed out"

### ISSUE THREAD

**Issue by qingzi02010** [chaofengc/IQA-PyTorch#198]
首先感谢您的工作和分享！测试时遇到下面问题：

运行pyiqa.create_metric时总是fail，  出现以下错误  raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

不知道别人是否有这个问题，我试了很多次都卡在了这里不能在线下载，请问能否支持：把模型上传到百度云，然后离线加载本地模型，或者其他建议，感谢！

**Comment by InTheFuture7** [comment]
@qingzi02010 您好，请问如何离线加载本地模型？我按下面的方法一直加载不上，报错`SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443)`

详见：https://github.com/chaofengc/IQA-PyTorch/issues/193#issuecomment-3144352517
