### ISSUE TITLE
Bug with incorrect setting of num_patch in LIQE

### ISSUE THREAD

**Issue by avermilov** [chaofengc/IQA-PyTorch#200]
Hello!

In the LIQE architecture file forward method https://github.com/chaofengc/IQA-PyTorch/blob/f5be993715437fbf31a56142daeb3161bb91a677/pyiqa/archs/liqe_arch.py#L110 if we encounter an image that has generated less than self.num_patch crops, we assign the self.num_patch variable to this smaller image size permanently, which would result in any subsequent forward calls to be using less than the initially set number of patches.

Perhaps I missed something, but shouldn't we get rid of the line 110 and replace all the later calls to self.num_patch with the local variable num_patch? This way the smaller than default number of patches would only impact the current forward.

Thank you in advance for your response!

**Comment by chaofengc** [comment]
Thank you so much for helping identify this bug! It has been fixed in the latest version.
