### ISSUE TITLE
[bug] Train DBCNN raise KeyError: 'type'

### ISSUE THREAD

**Issue by Kekwi** [chaofengc/IQA-PyTorch#204]
**cmmd**: python pyiqa/train.py -opt options/train/DBCNN/train_DBCNN.yml
**output**:
.....  (features2): Sequential(
    (0): Conv2d(3, 48, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv2d(48, 48, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (4): BatchNorm2d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): Conv2d(48, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (8): ReLU(inplace=True)
    (9): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (10): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (11): ReLU(inplace=True)
    (12): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (14): ReLU(inplace=True)
    (15): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (16): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (17): ReLU(inplace=True)
    (18): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (19): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (20): ReLU(inplace=True)
    (21): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (22): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (23): ReLU(inplace=True)
    (24): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (25): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (26): ReLU(inplace=True)
  )
  (fc): Linear(in_features=65536, out_features=1, bias=True)
)

Traceback (most recent call last):
  File "/xxxx/IQA-PyTorch/pyiqa/train.py", line 250, in <module>
    train_pipeline(root_path)
  File "/xxxx/IQA-PyTorch/pyiqa/train.py", line 138, in train_pipeline
    model = build_model(opt)
  File "/xxxx/IQA-PyTorch/pyiqa/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/xxxx/IQA-PyTorch/pyiqa/models/dbcnn_model.py", line 20, in __init__
    super(DBCNNModel, self).__init__(opt)
  File "/xxxx/IQA-PyTorch/pyiqa/models/general_iqa_model.py", line 33, in __init__
    self.init_training_settings()
  File "/xxxx/IQA-PyTorch/pyiqa/models/general_iqa_model.py", line 38, in init_training_settings
    self.net_best = build_network(self.opt['network']).to(self.device)
  File "/xxxx/IQA-PyTorch/pyiqa/archs/__init__.py", line 127, in build_network
    network_type = opt.pop('type')
KeyError: 'type'

**Comment by Kekwi** [comment]
and I checkout the version to v0.1.12 , it worked

**Comment by chaofengc** [comment]
Fixed at 140060df4404c16400507454ed52b080c22019fb
