### ISSUE TITLE
TOPIQ model

### ISSUE THREAD

**Issue by ctxya1207** [chaofengc/IQA-PyTorch#206]
Please tell me where can I find the original model of TOPIQA

**Comment by chaofengc** [comment]
please use the command `pyiqa --ls | grep topiq` to show all the available TOPIQA metrics.

**Comment by ctxya1207** [comment]
> please use the command `pyiqa -ls | grep topiq` to show all the available TOPIQA metrics.

Maybe you misunderstood what I meant. I want to understand the overall model architecture of TOPIQ.
