### ISSUE TITLE
General question about normalization

### ISSUE THREAD

**Issue by Eddudos** [chaofengc/IQA-PyTorch#209]
Is there an universal way of how am I suppose to normalize image? 
In particular I'm asking about **brisque** metric, should I run normalization using mean and std from ImageNet (or any other mean/std) or it is just normalization to interval [0, 1]?

Searched in docs, issues and readme, haven't found a proper answer.

**Comment by chaofengc** [comment]
Simply normalize the input to a [0, 1] range. Additional preprocessing steps, like ImageNet mean and standard deviation adjustments, are handled within each metric.

**Comment by Eddudos** [comment]
Thank you for fast answer! 
Issue can be closed now
