### ISSUE TITLE
提供TOPIQ_FR KADID10K数据集的训练配置文件

### ISSUE THREAD

**Issue by Younger6163** [chaofengc/IQA-PyTorch#211]
大佬，你好，能否提供一个针对TOPIQ_FR模型的数据集训练配置文件，比如KADID10K数据集，谢谢

**Comment by chaofengc** [comment]
请参考其它NR的训练配置文件，现有的模型参数，以及论文的训练细节，自行实验。并不需要特别的训练技巧。
