### ISSUE TITLE
The checkpoints for ARNIQAs are lost

### ISSUE THREAD

**Issue by YYue000** [chaofengc/IQA-PyTorch#214]
Got 404 when using pyiqa.create_metric('arniqa') and wget https://huggingface.co/chaofengc/IQA-PyTorch-Weights/resolve/main/ARNIQA.pth.

Could you upload it again?

**Comment by chaofengc** [comment]
Duplicate of #195

**Comment by chaofengc** [comment]
Thank you for the information. The weights have been uploaded to huggingface.
