### ISSUE TITLE
When modeltype is clipiqa, the network weight of CLIP is frozen and the prompt is fixed. What parameters are you training at this point?

### ISSUE THREAD

**Issue by akasupercode** [chaofengc/IQA-PyTorch#218]
When modeltype is clipiqa, the network weight of CLIP is frozen and the prompt is fixed. What parameters are you training at this point?

![image](https://github.com/user-attachments/assets/6097463f-e9ea-439e-8170-2ede52f63833)
![image](https://github.com/user-attachments/assets/53a271e2-2f56-40bc-84b3-9dbfe6ae164d)

**Comment by chaofengc** [comment]
Kindly refer to the original paper https://arxiv.org/abs/2207.12396  for addressing research-related queries. This repository's issue tracker is not intended for addressing such questions. Thank you for your understanding.
