### ISSUE TITLE
The following error is reported during the benchmark test: TypeError: 'weights_only' is an invalid keyword argument for Unpickler()

### ISSUE THREAD

**Issue by akasupercode** [chaofengc/IQA-PyTorch#219]
error:
![image](https://github.com/user-attachments/assets/df8f8afe-d769-48fb-997c-cd8d77bb9f5d)

configuration：
![image](https://github.com/user-attachments/assets/3f7af3c2-b98d-4d6d-9a43-f0cfdd93ee82)

**Comment by chaofengc** [comment]
please update pytorch to newer version >=1.13
