### ISSUE TITLE
download the .pkl file

### ISSUE THREAD

**Issue by yuweiiiii** [chaofengc/IQA-PyTorch#221]
Hello, thank you very much for your work! I found that there is no .pkl file in the link https://huggingface.co/datasets/chaofengc/IQA-Toolbox-Datasets-metainfo, only .csv file. Where can I download the .pkl file?

**Comment by chaofengc** [comment]
The `.pkl` file has been merged into meta info `.csv` file. You only need to use the `split_index` to specify split information. For example, use `split_index: official_split` to get official train split. Please refer to dataset cards for more details.

If you still need the original `pkl` file, you may download from here: https://github.com/chaofengc/IQA-PyTorch/releases/download/v0.1-weights/meta_info.tgz

**Comment by yuweiiiii** [comment]
Thank you very much!

**Comment by totravel** [comment]
@chaofengc Could you offer a script to merge split info into meta info file, as the dataset preprocessing scripts under scripts folder remain outdated and still generate standalone split files?
