### ISSUE TITLE
supporting koniq models

### ISSUE THREAD

**Issue by YYue000** [chaofengc/IQA-PyTorch#222]
Hi,

The implementations of 'arniqa-koniq','maniqa-koniq','musiq-koniq','tres-koniq' are missing in current version (0.1.13 via pip). These methods were available in the previous version. Are you going to support them in the next version?

Thanks.

**Comment by chaofengc** [comment]
The `koniq` model is the default configuration, identical to the base model without a suffix. To simplify naming, this suffix has been removed in the latest version.

**Comment by YYue000** [comment]
Hello,

Thanks for your reply. Then in the previous version, what are those metrics without a suffix? Are they also models on koniq?

**Comment by chaofengc** [comment]
As in the reply above, they are identical and exactly the same
