### ISSUE TITLE
About methods for fast Image Quality Assessment in NR Method

### ISSUE THREAD

**Issue by Danee-wawawa** [chaofengc/IQA-PyTorch#26]
Hi, thanks for your work. I want to learn about fast IQA methods in NR Method. do you have any recommendations? 
Among the methods supported by your current project, is there a faster method?
Looking forward to your reply.

**Comment by chaofengc** [comment]
With GPU acceleration, most of the supported NR methods are quite fast.
Without GPU, you may try the widely-used NIQE and BRISQUE.
