### ISSUE TITLE
Are you considering supporting other IQA algorithms? Such as `SNR` evaluation method

### ISSUE THREAD

**Issue by Lornatang** [chaofengc/IQA-PyTorch#27]
SNR [(Wiki) https://en.wikipedia.org/wiki/Signal-to-noise_ratio](https://en.wikipedia.org/wiki/Signal-to-noise_ratio)

Thanks. Avesome IQA toolbox

**Comment by chaofengc** [comment]
You may refer to PSNR https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio
SNR is not usually used for IQA.
