### ISSUE TITLE
different NIQE  with Matlab

### ISSUE THREAD

**Issue by greatlog** [chaofengc/IQA-PyTorch#28]
Thanks for your awesome work.

I find some problems when I use pyiqa to calculate the NIQE score. It seems the result calculated by pyiqa is different from that of Matlab.

```
import matlab.engine
import matlab

import torch
import pyiqa

im = cv2.imread("img.png")


## calculate via matlab
eng = matlab.engine.start_matlab()
im_m = matlab.uint8(im.tolist())
niqe_matlab = eng.niqe(im_m)

## calculate via pyiqa
im_t = torch.FloatTensor(im.transpose(2,0,1)[None]).cuda() / 255.0
niqe_fn = pyiqa.create_metric("niqe")
niqe_pyiqa = niqe_fn(im_t)
```

**Comment by chaofengc** [comment]
Please note that we use the official codes and parameters [here](https://github.com/utlive/niqe) rather than the default function in matlab.

**Comment by greatlog** [comment]
So the default function in Matlab is different from the official one. 

I get it.

Thanks.

**Comment by chaofengc** [comment]
Yes, NIQE has some parameters to learn. To ensure consistent behavior, we use the official parameters. And we did not get the default parameters used in matlab either.
