### ISSUE TITLE
./datasets/train_split_info/koniq10k_official.pkl

### ISSUE THREAD

**Issue by junedwx** [chaofengc/IQA-PyTorch#29]
Hi，I want to test the prediction accuracy of MUSIQ and calculate plcc and srocc. Where can I get'./datasets/train_split_info/koniq10k_official.pkl'?

**Comment by chaofengc** [comment]
Please check the download scripts in `Dataset preparation` part of README.

**Comment by junedwx** [comment]
Thank you for your reply！
