### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by maywander** [chaofengc/IQA-PyTorch#30]
在使用tid2008训练DBCNN时，在使用reference images与distorted images训练时，(https://github.com/chaofengc/IQA-PyTorch/tree/main/pyiqa/models)/general_iqa_model.py 第85行 return net(self.img_input, self.ref_input) 报错TypeError: forward() takes 2 positional arguments but 3 were given。请问有什么解决办法吗
![3](https://user-images.githubusercontent.com/38091087/180696766-c8595dc8-2185-43cb-8385-591669012e6a.PNG)
@chaofengc

**Comment by chaofengc** [comment]
Fixed by adding `use_ref` option.
https://github.com/chaofengc/IQA-PyTorch/blob/829d26a1b5118a3f53b69b26bc59523b1fc42dc0/options/train/DBCNN/train_DBCNN_tid.yml#L53
