### ISSUE TITLE
possibly missing import for read_meta_info_file

### ISSUE THREAD

**Issue by JuliBaCSE** [chaofengc/IQA-PyTorch#31]
https://github.com/chaofengc/IQA-PyTorch/blob/0b6738d093821ba81392fea97aa6404eded42b1b/pyiqa/data/livechallenge_dataset.py#L33

hey, I wanted to test the train script from your amazing repo. But I always encounter the error of read_meta_info_file is not defined. I guess the import is missing in live challenge_dataset.py

**Comment by chaofengc** [comment]
Thanks for your info. Fixed by adding the import.
