### ISSUE TITLE
Passing Images as Tensors

### ISSUE THREAD

**Issue by pentanol2** [chaofengc/IQA-PyTorch#33]
Hi. Is it possible or is there any way to pass images as a tensors instead of passing them as paths or filenames to perform inference

**Comment by chaofengc** [comment]
Please note that the interface supports both filename and tensors as inputs, for example
```
# example for iqa score inference
# Tensor inputs, img_tensor_x/y: (N, 3, H, W), RGB, 0 ~ 1
score_fr = iqa_metric(img_tensor_x, img_tensor_y)
score_nr = iqa_metric(img_tensor_x)
```

Please read the `basic usage` section in readme for more examples.

**Comment by pentanol2** [comment]
Once I try that method I get the folllowing error . 'array is not a valid image file'

**Comment by pentanol2** [comment]
> Please note that the interface supports both filename and tensors as inputs, for example
> 
> ```
> # example for iqa score inference
> # Tensor inputs, img_tensor_x/y: (N, 3, H, W), RGB, 0 ~ 1
> score_fr = iqa_metric(img_tensor_x, img_tensor_y)
> score_nr = iqa_metric(img_tensor_x)
> ```
> 
> Please read the `basic usage` section in readme for more examples.



> Please note that the interface supports both filename and tensors as inputs, for example
> 
> ```
> # example for iqa score inference
> # Tensor inputs, img_tensor_x/y: (N, 3, H, W), RGB, 0 ~ 1
> score_fr = iqa_metric(img_tensor_x, img_tensor_y)
> score_nr = iqa_metric(img_tensor_x)
> ```
> 
> Please read the `basic usage` section in readme for more examples.

Once I try that method I get the folllowing error . 'array is not a valid image file'

**Comment by chaofengc** [comment]
Please follow the demo instructions to use the functions, which are purely based on pytorch.
Note the input should be pytorch tensor, with the following format
```
# Tensor inputs, img_tensor_x/y: (N, 3, H, W), RGB, 0 ~ 1
```
