### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by nicolasch96** [chaofengc/IQA-PyTorch#35]
Hello,

Is there any chance to get weights for pretrained models ?

Thank you in advance.

**Comment by chaofengc** [comment]
Many models are stored [here](https://github.com/chaofengc/IQA-PyTorch/releases/tag/v0.1-weights), and can be downloaded automatically. You may report the missing weights when using our tools. And we will update them in near future.

**Comment by nicolasch96** [comment]
Thank you very much for your response.

For now a CNNIQA model is missing, and I guess you should put a link to ./experiments/pretrained_models/DBCNN/scnn.pkl' which I found here: "https://github.com/zwx8981/DBCNN-PyTorch/blob/master/pretrained_scnn/scnn.pkl"
