### ISSUE TITLE
Where is Maniqa?

### ISSUE THREAD

**Issue by andreaferretti** [chaofengc/IQA-PyTorch#41]
I see that Maniqa is listed as one of the available metrics. Yet, when I call `pyiqaa.list_models()`, I get

```py
['brisque',
 'ckdn',
 'cw_ssim',
 'dbcnn',
 'dists',
 'fid',
 'fsim',
 'gmsd',
 'ilniqe',
 'lpips',
 'lpips-vgg',
 'mad',
 'ms_ssim',
 'musiq',
 'musiq-ava',
 'musiq-koniq',
 'musiq-paq2piq',
 'musiq-spaq',
 'nima',
 'niqe',
 'nlpd',
 'nrqm',
 'paq2piq',
 'pi',
 'pieapp',
 'psnr',
 'ssim',
 'vif',
 'vsi']
```

even though I have installed the latest version with `pip install git+https://github.com/chaofengc/IQA-PyTorch.git`.

Is there a way to find the missing models?

**Comment by chaofengc** [comment]
You may need to uninstall previous installation. The latest version should support `maniqa`. Please refer to the colab demo.

**Comment by andreaferretti** [comment]
I uninstalled and reinstalled and now it works, thank you!
