### ISSUE TITLE
NIQE metric doesnot work

### ISSUE THREAD

**Issue by sanjaybhandarii** [chaofengc/IQA-PyTorch#43]
There is an issue in NIQE model, I passed a tensor list of images in form [8,3,32,32] but it shows following error:

-> 4381     return torch._C._nn.replication_pad2d(input, pad)
   4382 elif mode == "circular":
   4383     return _pad_circular(input, pad)
**RuntimeError: Expected 3D or 4D (batch mode) tensor with possibly 0 batch size and other non-zero dimensions for input, but got: [8, 1, 0, 0]**

**Comment by chaofengc** [comment]
Please note that the official niqe use default block size of `96x96`, and is not applicable to images smaller than that. You may try `brisque` instead.
