### ISSUE TITLE
The results are different every time I run the same image

### ISSUE THREAD

**Issue by wangfeng6909** [chaofengc/IQA-PyTorch#48]
Hi, thanks for your work. I tried using maniqa, but every time I run it with the same image, the result is different, is this normal?

**Comment by chaofengc** [comment]
Yes, this is expected because maniqa samples 20 patches of size 224x224 **randomly** for score prediction. See codes below:

https://github.com/chaofengc/IQA-PyTorch/blob/3619109b4491d685837a795549db1f948fc19cc6/pyiqa/archs/maniqa_arch.py#L172-L175
