### ISSUE TITLE
Add clip to requirements.txt

### ISSUE THREAD

**Issue by Godofnothing** [chaofengc/IQA-PyTorch#51]
Thanks for a great library and your effort. 

I think that you need add `clip` to `requirements.txt`. 

CLIP-IQA metric requires a `clip` package ([this one](https://github.com/openai/CLIP)).  

Otherwise `import pyiqa` will fail:
```
~/IQA-PyTorch/pyiqa/archs/clipiqa_arch.py:23
ModuleNotFoundError: No module named 'clip'
```

**Comment by chaofengc** [comment]
Thanks for help. Fixed at 466b3d1.
