### ISSUE TITLE
Bug: pip install fails since CLIP dependency was added

### ISSUE THREAD

**Issue by snk4tr** [chaofengc/IQA-PyTorch#52]
### Observed behavior
Since CLIP [dependency was added](https://github.com/chaofengc/IQA-PyTorch/commit/466b3d12fa66c76ab2faa49c2a9a90098163fd91), the following error occurs:
```bash
$ python setup.py develop
>>> error in pyiqa setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'+https:/'": Expected string_end
```

The same problem occurs for PyPi installation:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/24959314/212891646-39b372eb-2e6f-4800-85cd-84e845fc769b.png">

However, installation from the [previous commit](https://github.com/chaofengc/IQA-PyTorch/commit/4c5314cf45345c95ee879f1a4cf4d9c210436739) leads to successful installation:
```bash
$ pip install git+https://github.com/chaofengc/IQA-PyTorch.git@4c5314cf45345c95ee879f1a4cf4d9c210436739
>>> Successfully built pyiqa
>>> Installing collected packages: pyiqa
>>> Successfully installed pyiqa-0.1.5
```

### Expected behavior
Both `git clone` and `pip install` commands lead to successful installation.

**Comment by chaofengc** [comment]
Thanks for help. The bug is fixed at [53d176f](https://github.com/chaofengc/IQA-PyTorch/commit/53d176f695fb418946c9e29b7fb141267828541f)
