### ISSUE TITLE
paq2piq

### ISSUE THREAD

**Issue by zhanghongruiupup** [chaofengc/IQA-PyTorch#54]
Hi, how to train Model paq2piq？no yaml file found

**Comment by chaofengc** [comment]
Please be advised that for models such as paq2piq that utilize official weights, we do not have plans to retrain them as it is time-consuming to ensure identical training conditions. As a result, there are no accompanying yaml files for these models.

If you wish to train the model yourself, it should be straightforward to create the yaml file. Just make sure to thoroughly read the relevant paper and use the exact same training configurations.

We would greatly appreciate it if you could reproduce the results and contribute to our repository. Thank you!
