### ISSUE TITLE
MANIQA training

### ISSUE THREAD

**Issue by Ashutosh1995** [chaofengc/IQA-PyTorch#60]
Hi @chaofengc,

Thanks for open-sourcing this repo!

Do you have MANIQA for retraining? I can see the architecture in archs.py but nothing in the options/train folder.

**Comment by chaofengc** [comment]
Thank you for your interest in the repository and your question!

Unfortunately, we don't have scripts specifically for retraining with MANIQA in the options/train folder. However, you can train your own models using the architecture defined in archs.py.

To do this, you will need to write a training script that utilizes the architecture and data loading pipeline to train a model on your dataset. You can find some examples of training scripts in the options/train folder that you can modify to fit your needs.

Additionally, you'd better read the original paper carefully and make sure the training settings are correct.

**Comment by Ashutosh1995** [comment]
Hey @chaofengc ,

Thanks for the reply!

I had one more query. In a recent accepted paper https://arxiv.org/pdf/2302.09838.pdf, the authors mention results of MANIQA on KonIQ dataset. The splitting which this paper mentioned or the one that MANIQA mentions for NR datasets like KonIQ is a normal splitting of main set into train and test right? Or is it some special form of splitting operation that they perform?        

Kindly clarify!

**Comment by chaofengc** [comment]
Sorry that I did not read this paper. As for the split of different datasets, you may refer to the dataset preparation here:

https://github.com/chaofengc/IQA-PyTorch/blob/1baa70ee70c9c05747d2ba8b56bc3aa8f46fc7fd/docs/Dataset_Preparation.md?plain=1#L52-L58

I have tried to collected the official splits as many as I can. However, different papers may use different splits.

**Comment by Ashutosh1995** [comment]
Thanks @chaofengc, for your reply! I saw the pkl files containing the split information. Many recent papers like MUSIQ, MANIQA and TReS and others as well split the official datasets into 80% train and 20% test and then create multiple such splits. Same I see in your codebase for LIVEC dataset but not for KonIQ. Is there any reason for it?

**Comment by chaofengc** [comment]
We follow official splits when it is available, such as KonIQ.
