### ISSUE TITLE
Possibly a little bug in /pyiqa/archs/ahiq_arch.py

### ISSUE THREAD

**Issue by PenguinQwQ** [chaofengc/IQA-PyTorch#65]
Line 221 is "cnn_dis = self.deform_net(cnn_dis, vit_ref)", but I think here is  "cnn_dis = self.deform_net(cnn_dis, vit_dis)" to get the fused feature.

**Comment by chaofengc** [comment]
Thanks for your interest. The code follows exactly the official repo and we have checked the validation performance. 

https://github.com/IIGROUP/AHIQ/blob/9cc6a4eed821bb8f16a1aae00d420b24625bc07a/train.py#L158

You may double check the original codes and paper.

**Comment by chaofengc** [comment]
Please note that the model is trained on PIPAL dataset. There are no official models trained on other datasets. You may have to retrain the model by yourself to get the model performance on TID2013 and other dataset. 

Wish you all the best for your research
