### ISSUE TITLE
NIQE指标，PI指标是否存在问题

### ISSUE THREAD

**Issue by automatic0313** [chaofengc/IQA-PyTorch#67]
您好，请问我用您的代码测试NIQE指标，PI指标和用Pirm-2018测出的结果有较大的差异，是否代码存在问题？

**Comment by chaofengc** [comment]
请给出问题测试样例

**Comment by automatic0313** [comment]
我利用您的代码生成的NIQE指标为4.411269179158866，PI指标为3.697619367030163 
（使用命令为 python inference_iqa.py -m NRQM -i）
使用matlab利用Pirm-2018代码 NIQE指标为4.7157        PI指标为4.3848
![00000000](https://user-images.githubusercontent.com/49469941/228451294-df05769d-8f37-4520-83b1-d055e6c5111f.png)

**Comment by chaofengc** [comment]
感谢你的反馈。经排查，问题出在NRQM的计算上。已经在最新的commit中修复: 257f24ea1297a0a7d20fa0c511ab9ba734ed15d0

可由如下命令更新到最新版本:
```
pip uninstall pyiqa # if have older version installed already 
pip install git+https://github.com/chaofengc/IQA-PyTorch.git
```
-------------------------------------------
详细解答如下:

**Q1: 之前版本的PI计算出了什么问题**

`PI = 0.5 * (10 - NRQM + NIQE)` 在之前的版本中，NRQM的计算有bug。具体原因是NRQM调用了SSIM，但是只使用了structure similarity。之前版本忽略了这点，非常抱歉。

**Q2: 为什么直接用NIQE和PI里的NIQE计算结果不同**

PI里的NIQE和官方的NIQE版本有两点区别: (1) PI裁减了边框；(2) PI使用了`rgb2ycbcr`而不是原始版本的`rgb2gray`函数。Fix后，当前版本计算结果为: **PI: 4.3845 with NIQE=4.7167; NRQM=5.9476**

**Q3: 为什么仍然存在一定误差**

由于某些函数（例如torch.svd）的精度上与matlab有一定差别，本Toolbox的结果与matlab版本有一定的误差。但数值误差不应大于5%，一般在1%以内。我们随机挑选了五张图作为校准测试，结果见[ResultsCalibra](https://github.com/chaofengc/IQA-PyTorch/blob/main/ResultsCalibra/ResultsCalibra.md)中的表格。因为精力有限，我们无法测试很多的corner case。欢迎你使用我们的工具并提供更多反馈。
