### ISSUE TITLE
FID Verbose

### ISSUE THREAD

**Issue by Serendipity-55428** [chaofengc/IQA-PyTorch#71]
Is line 253-254 of `/pyiqa/archs/fid_arch.py` supposed to be `if verbose: print("compute FID between two folders")`? When I set verbose = False, I don't want a detailed output print, but line 253-254 now is `if not verbose: print("compute FID between two folders")`, it printed and caused my tqdm to not display properly, Thanks!

**Comment by chaofengc** [comment]
Thanks to your feedback. Fixed in latest commit 49b2297

**Comment by Serendipity-55428** [comment]
老哥效率真高，已三连

**Comment by Serendipity-55428** [comment]
老哥能加个联系方式吗？我还发现几个问题，要不直接微信跟你说，就不在GitHub上提Issue了

**Comment by chaofengc** [comment]
好的，老哥。我微信号是: ccf_fly
