### ISSUE TITLE
MANIQA Checkpoints updates

### ISSUE THREAD

**Issue by TianheWu** [chaofengc/IQA-PyTorch#73]
Hi, I release the newest MANIQA checkpoints.

**Comment by chaofengc** [comment]
Thanks to your great work. Will add to our repo soon.

**Comment by TianheWu** [comment]
你好，感谢您整理的IQA框架，我们在用您的框架的时候遇到了一些问题，不是关于工程上的，是我们在做实验的时候，发现的一些问题，这些问题可能需要知晓一些内部实现细节才能解决。请问方便和您取得联系方式么，我的微信是：15601049245，来自清华大学。
