### ISSUE TITLE
AHIQ does not propagate gradients

### ISSUE THREAD

**Issue by maximelianos** [chaofengc/IQA-PyTorch#76]
Hello! I create the AHIQ model, and want to propagate gradients:
`model = pyiqa.create_metric('ahiq', as_loss=True, device=DEVICE)`

However, gradient of the image tensor `image.grad` is None. I removed lines in AHIQ where gradient is disabled, and it works
https://github.com/chaofengc/IQA-PyTorch/blob/main/pyiqa/archs/ahiq_arch.py#L175
https://github.com/chaofengc/IQA-PyTorch/blob/main/pyiqa/archs/ahiq_arch.py#L191

**Comment by chaofengc** [comment]
Thanks for your information ! Fixed at 1947903ae923187a0fc5fc35ea65a8a3b9b2b455
