### ISSUE TITLE
NIQE question

### ISSUE THREAD

**Issue by Hattfield** [chaofengc/IQA-PyTorch#77]
```python
import numpy as np
from torchvision.transforms.functional import to_tensor
import torch
import imageio
import pyiqa
from PIL import Image
import cv2

if __name__ == "__main__":
    img = np.random.randint(200, 255, (250, 400)).astype(np.uint8)
    # print(img.shape)
    # cv2.imshow("0", img)
    # cv2.waitKey(2000)
    img = to_tensor(img).unsqueeze(0)
    niqe = pyiqa.create_metric('niqe', device="cpu")
    print(niqe(img))
```
If a generated numpy array which has close values was sent to niqe, an error would occur like this:
>invcov_param = torch.linalg.pinv((cov_pris_param + cov_distparam) / 2)
torch._C._LinAlgError: linalg.svd: (Batch element 0): The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values (error code: 16).

Nan appears to be the problem, as it exists in cov_distparam. And some light pic will also encounter the same problem.

Would you please fix it or tell me how to deal with the problem? Thank you!

**Comment by chaofengc** [comment]
Thanks for your feedback. Current version only consider image input with RGB channels, I have fixed it for niqe 212ecefebd466cac019a1678e1b3a4e0378face0
