### ISSUE TITLE
DBCNN image size

### ISSUE THREAD

**Issue by hazelAutumn** [chaofengc/IQA-PyTorch#81]
Hi,
I have a question about the input image of DBCNN. In the original paper, they mentioned that the input images are resized to 256x256x3, then cropped to 224x224x3. But in your code, it seems like the input images are not processed in the same way. They are only normalized so that their pixel values are in the range  [0,1] and can be in any size.

Am I understanding it right?
Thanks,

**Comment by chaofengc** [comment]
Yes, since the network design of DBCNN does not require strict 224x224 inputs, our implementation also does not make such constrain for simplicity.

**Comment by hazelAutumn** [comment]
Thank you so much for your quick reply!
