### ISSUE TITLE
AVA数据集的标准划分

### ISSUE THREAD

**Issue by Zdxfgre** [chaofengc/IQA-PyTorch#84]
想问下能否提供下AVA数据集的标准划分文件，即代码中的‘official_test_challenges.txt’文件？从AVA对应的项目地址里好像并没有找到对应的数据集划分表格，非常疑惑。

**Comment by chaofengc** [comment]
AVA数据集中的chanllenge id包含了官方的test split:
https://github.com/imfing/ava_downloader/blob/master/AVA_dataset/challenges.txt

**Comment by Zdxfgre** [comment]
了解了，感谢您的解答

**Comment by chaofengc** [comment]
抱歉，最近检查代码后发现之前给的split信息有误，正确的split应该是以下链接
https://github.com/imfing/ava_downloader/blob/master/AVA_dataset/aesthetics_image_lists/generic_test.jpgl

这里包含了20,000个image name，其中有些image id已失效，本项目中实际测试样本数量为19930
