### ISSUE TITLE
IQA Transformer Models

### ISSUE THREAD

**Issue by Stevieee83** [chaofengc/IQA-PyTorch#89]
Hello, if the model is available from the library without a dataset in the title, does this mean that the model is fine-tuned on a default dataset or has not been fine-tuned?

I understand that the larger transformer models are trained on ImageNet and then fine-tuned on a smaller IQA dataset for downstream tasks. From the information in the MUSIQ publication, I assume that MUSIQ-paq2piq is trained on ImageNet and then fine-tuned on the PaQ2PiQ dataset.

I look forward to your response, and thanks for your time.

**Comment by chaofengc** [comment]
The provided models without a dataset are directly taken from the official implementations. The information about the corresponding dataset is not added to our repo yet. For now, you have to look into the original repo to know the training information.

For models based on large backbones, they depend on the pretrained models from the [pytorch-image-models](https://github.com/huggingface/pytorch-image-models) project from hugging face 🤗. Then, finetuned with IQA datasets.

**Comment by Stevieee83** [comment]
That's great, and thanks for your response. Thanks also for taking the time to provide a helpful link to anther GitHub repository.

All the best.
