### ISSUE TITLE
Missing `lower_better` items in configs

### ISSUE THREAD

**Issue by ryanxingql** [chaofengc/IQA-PyTorch#97]
Hi @chaofengc, thanks for your work!

Why there are some items in `pyiqa/default_model_configs.py` that do not indicate the `lower_better`?

For example, for FID, lower FID indicates better fidelity. However, the output of `fid_metric.lower_better` is `False`, which is confusing.

**Comment by chaofengc** [comment]
Thanks to your remind. The `lower_better` for `fid` has been fixed.

The default `lower_better` attribute is set to `False` and we only specify metric with `lower_better=True` in the config file.
