### ISSUE TITLE
Difference BRISQUE score from opencv for the same image

### ISSUE THREAD

**Issue by 3dimaging** [chaofengc/IQA-PyTorch#98]
Hi, Thank you for your great work! I tested the brisque metric from your package and compared it with the one from opencv. I found the IQA-Pytorch gives a brisque score of 54.0558, but the brisque score from opencv is 13.4364.
Could you explain the difference? is the model different?

**Comment by chaofengc** [comment]
please note that our implementation follows the original implementation released by the authors: https://github.com/utlive/BRISQUE/tree/main/MATLAB
