### ISSUE TITLE
Inconsistent output of MAD score to IQA-optimization's version

### ISSUE THREAD

**Issue by nmhkahn** [chaofengc/IQA-PyTorch#99]
Thank you for the great project!

While testing some of the metrics, I noticed that the MAD score doesn't align with [dingkeyan93/IQA-optimization](https://github.com/dingkeyan93/IQA-optimization/blob/master/IQA_pytorch/MAD.py), even though the PR author borrowed from (https://github.com/chaofengc/IQA-PyTorch/pull/11).

I haven't fully explored the code, but I suspect the issue might be with the fft-related parts. For instance, in [L140](https://github.com/chaofengc/IQA-PyTorch/blob/main/pyiqa/archs/mad_arch.py#L140C5-L140C28), the PR author modifies the fft code to (to compatible to the newer pytorch version as in > 1.8 fft goes to torch.fft instead of fft):
```python
x = torch.fft.fft2(ref)
```
However, for consistency with the original code, it should be:
```python
x = torch.view_as_real(torch.fft.fftn(ref, dim=(-2, -1)))
```
Other fft-related sections may need similar changes.

**Comment by chaofengc** [comment]
Thanks for your information.

The implementation is the same as [dingkeyan93/IQA-optimization](https://github.com/dingkeyan93/IQA-optimization/blob/master/IQA_pytorch/MAD.py). The difference comes from the fact that we use the luminance channel by default.

I have changed the default `test_y_channel` option to `False` to make it consistent with [dingkeyan93/IQA-optimization](https://github.com/dingkeyan93/IQA-optimization/blob/master/IQA_pytorch/MAD.py) and work better on color image.
